# Generated by Django 5.2 on 2025-04-23 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helptopic',
            options={'verbose_name_plural': 'Topicos de Ajuda'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'verbose_name_plural': 'Anexos de Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'verbose_name_plural': 'Comentarios de Tickets'},
        ),
        migrations.RemoveField(
            model_name='helptopic',
            name='description',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
