# Generated by Django 5.2 on 2025-04-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_helptopic_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_progress', 'Em Progress'), ('fechado', 'Fechado')], default='open', max_length=20),
        ),
    ]
