# Generated by Django 5.2 on 2025-04-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Em progresso', 'Em Progresso'), ('Fechado', 'Fechado')], default='open', max_length=20),
        ),
    ]
