# Generated by Django 5.2 on 2025-04-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_progresso', 'Em Progresso'), ('fechado', 'Fechado')], default='open', max_length=20),
        ),
    ]
