# Generated by Django 5.2 on 2025-05-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_tasks_created_at_tasks_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_status',
        ),
    ]
