# Generated by Django 5.2 on 2025-05-02 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0011_remove_tasks_task_status'),
        ('users', '0003_alter_agents_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to='users.agents'),
        ),
    ]
