# Generated by Django 5.2 on 2025-05-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_remove_ticket_created_by_tasks_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
