# Generated by Django 5.2 on 2025-05-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0016_ticketactivitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketactivitylog',
            old_name='action',
            new_name='info',
        ),
    ]
