# Generated by Django 5.2 on 2025-05-14 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0017_rename_action_ticketactivitylog_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketactivitylog',
            options={'verbose_name_plural': 'Logs de Actividades dos Ticket'},
        ),
        migrations.CreateModel(
            name='TaskActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(verbose_name='Actividade')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Registo')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tasks', verbose_name='Tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Logs de Actividades das Tarefas',
            },
        ),
    ]
