# Generated by Django 5.2 on 2025-05-15 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_alter_ticketactivitylog_options_taskactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivitylog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='helpdesk.tasks', verbose_name='Tarefa'),
        ),
    ]
