# Generated by Django 5.2 on 2025-05-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0020_alter_taskactivitylog_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskactivitylog',
            name='user',
        ),
        migrations.AddField(
            model_name='taskactivitylog',
            name='username',
            field=models.CharField(default='', verbose_name='Nome do Usuário'),
        ),
        migrations.AlterField(
            model_name='taskactivitylog',
            name='task',
            field=models.CharField(default='', verbose_name='Tarefa'),
        ),
    ]
