# Generated by Django 5.2 on 2025-05-15 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0021_remove_taskactivitylog_user_taskactivitylog_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskactivitylog',
            name='username',
        ),
        migrations.AddField(
            model_name='taskactivitylog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskactivitylog',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tasks', verbose_name='Tarefa'),
        ),
    ]
