# Generated by Django 5.2 on 2025-05-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0022_remove_taskactivitylog_username_taskactivitylog_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskactivitylog',
            name='user',
        ),
        migrations.AddField(
            model_name='taskactivitylog',
            name='username',
            field=models.CharField(default=1, verbose_name='nome do usuário'),
        ),
        migrations.AlterField(
            model_name='taskactivitylog',
            name='task',
            field=models.CharField(default=1, verbose_name='Tarefa'),
        ),
    ]
