# Generated by Django 5.2 on 2025-05-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0024_remove_taskactivitylog_username_taskactivitylog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivitylog',
            name='task',
            field=models.CharField(verbose_name='Tarefa'),
        ),
        migrations.AlterField(
            model_name='taskactivitylog',
            name='user',
            field=models.CharField(verbose_name='Nome do Usuário'),
        ),
    ]
