# Generated by Django 5.2 on 2025-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0025_alter_taskactivitylog_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketactivitylog',
            name='ticket',
            field=models.CharField(verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='ticketactivitylog',
            name='user',
            field=models.CharField(verbose_name='Nome do Usuário'),
        ),
    ]
