# Generated by Django 5.2 on 2025-05-15 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0026_alter_ticketactivitylog_ticket_and_more'),
        ('users', '0003_alter_agents_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketpriorityhistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ticketpriorityhistory',
            name='ticket',
        ),
        migrations.AlterUniqueTogether(
            name='ticketstatushistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ticketstatushistory',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='helpdesk.ticket'),
        ),
        migrations.DeleteModel(
            name='TasksHistory',
        ),
        migrations.DeleteModel(
            name='TicketPriorityHistory',
        ),
        migrations.DeleteModel(
            name='TicketStatusHistory',
        ),
        migrations.AddField(
            model_name='tasks',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_tasks', to='users.agents'),
        ),
    ]
