# Generated by Django 5.2 on 2025-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0027_alter_ticketpriorityhistory_unique_together_and_more'),
        ('users', '0003_alter_agents_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='users.agents'),
        ),
    ]
