# Generated by Django 5.2 on 2025-04-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='privilege_level',
            field=models.CharField(choices=[('admin', 'Admin'), ('agente', 'Agente'), ('suporte', 'Suporte')], default='user', help_text='Select the privilege level for the agent.', max_length=20),
        ),
    ]
