# Generated by Django 5.2 on 2025-04-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_agents_privilege_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agents',
            options={'ordering': ['user__username'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
    ]
